package com.mcbot.ai;

/**
 * A single atomic task for the bot to execute.
 * Tasks are generated by the AI brain and executed in sequence.
 */
public class Task {

    public enum Type {
        MINE,           // mine specific blocks
        NAVIGATE,       // go to coordinates
        FARM,           // harvest crops
        BUILD,          // build from schematic
        FIGHT,          // enter combat mode
        CRAFT,          // craft an item
        EXPLORE,        // explore the world
        WAIT,           // wait N ticks
        CHAT,           // send a chat message
        CUSTOM          // raw Baritone command
    }

    public final Type type;
    public final String[] args;
    public String description;
    private boolean completed = false;
    private boolean failed = false;
    private String failReason = "";

    public Task(Type type, String description, String... args) {
        this.type = type;
        this.description = description;
        this.args = args;
    }

    public void markComplete() { this.completed = true; }
    public void markFailed(String reason) { this.failed = true; this.failReason = reason; }
    public boolean isCompleted() { return completed; }
    public boolean isFailed() { return failed; }
    public String getFailReason() { return failReason; }

    @Override
    public String toString() {
        return "[" + type + "] " + description;
    }
}
