package com.mcbot.ai;

import baritone.api.BaritoneAPI;
import baritone.api.pathing.goals.GoalBlock;
import baritone.api.pathing.goals.GoalXZ;
import com.mcbot.MCBotClient;
import com.mcbot.module.world.AutoMineModule;
import com.mcbot.module.world.AutoFarmModule;
import com.mcbot.module.world.BuilderModule;
import com.mcbot.module.world.ExplorationModule;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.Component;

import java.util.ArrayDeque;
import java.util.Deque;

/**
 * TaskQueue — executes tasks generated by the AI brain in order.
 *
 * The queue runs on the game tick thread. Each task is executed until
 * it completes or fails, then the next task begins.
 */
public class TaskQueue {

    private final Deque<Task> queue = new ArrayDeque<>();
    private Task current = null;
    private int taskTimeout = 0;
    private static final int MAX_TASK_TICKS = 12000; // 10 minutes max per task

    public void add(Task task) { queue.addLast(task); }
    public void clear() { queue.clear(); current = null; }
    public boolean isEmpty() { return queue.isEmpty() && current == null; }
    public Task getCurrent() { return current; }
    public int size() { return queue.size() + (current != null ? 1 : 0); }

    /** Called every game tick. */
    public void tick(Minecraft client) {
        if (current == null) {
            if (queue.isEmpty()) return;
            current = queue.poll();
            taskTimeout = 0;
            startTask(client, current);
        } else {
            taskTimeout++;
            if (taskTimeout > MAX_TASK_TICKS) {
                failCurrent(client, "Timeout");
                return;
            }
            checkCompletion(client, current);
        }
    }

    // ── Start a task ──────────────────────────────────────────────────────

    private void startTask(Minecraft client, Task task) {
        if (client.player == null) return;
        client.player.sendSystemMessage(Component.literal("[MC BOT] Task: " + task.description));

        var mm = MCBotClient.get().getModuleManager();

        switch (task.type) {
            case MINE -> {
                AutoMineModule mine = (AutoMineModule) mm.getModule("AutoMine");
                applyMineTarget(mine, task.args.length > 0 ? task.args[0] : "diamond");
                mine.enable();
            }
            case NAVIGATE -> {
                if (task.args.length >= 2) {
                    int x = Integer.parseInt(task.args[0]);
                    int z = Integer.parseInt(task.args[1]);
                    BaritoneAPI.getProvider().getPrimaryBaritone()
                            .getCustomGoalProcess().setGoalAndPath(new GoalXZ(x, z));
                }
            }
            case FARM -> {
                mm.getModule("AutoFarm").enable();
            }
            case BUILD -> {
                if (task.args.length > 0) {
                    BuilderModule builder = (BuilderModule) mm.getModule("Builder");
                    builder.startBuild(task.args[0]);
                    builder.enable();
                }
            }
            case FIGHT -> {
                mm.getModule("KillAura").enable();
            }
            case EXPLORE -> {
                mm.getModule("Exploration").enable();
            }
            case WAIT -> {
                // Just tick until timeout (args[0] = ticks to wait)
                int waitTicks = task.args.length > 0 ? Integer.parseInt(task.args[0]) : 20;
                taskTimeout = MAX_TASK_TICKS - waitTicks; // complete after N ticks
            }
            case CHAT -> {
                if (task.args.length > 0 && client.player != null) {
                    client.player.connection.sendChat(task.args[0]);
                }
                current.markComplete();
                current = null;
            }
            case CUSTOM -> {
                // Pass as Baritone command
                // baritone.getCommandManager().execute(task.args[0]);
                current.markComplete();
                current = null;
            }
        }
    }

    // ── Check if current task is done ─────────────────────────────────────

    private void checkCompletion(Minecraft client, Task task) {
        var mm = MCBotClient.get().getModuleManager();
        boolean done = false;

        switch (task.type) {
            case MINE -> {
                // Complete when Baritone stops (area exhausted) or inventory full
                done = !BaritoneAPI.getProvider().getPrimaryBaritone().getMineProcess().isActive();
                if (done) mm.getModule("AutoMine").disable();
            }
            case NAVIGATE -> {
                done = !BaritoneAPI.getProvider().getPrimaryBaritone().getPathingBehavior().isPathing();
            }
            case FARM -> {
                // Farm for a fixed duration or until crops done
                done = taskTimeout > 600; // 30 seconds
                if (done) mm.getModule("AutoFarm").disable();
            }
            case BUILD -> {
                BuilderModule builder = (BuilderModule) mm.getModule("Builder");
                done = !builder.isBuilding();
            }
            case FIGHT -> {
                done = taskTimeout > 200; // fight for 10 seconds then move on
                if (done) mm.getModule("KillAura").disable();
            }
            case EXPLORE -> {
                done = taskTimeout > 2400; // explore for 2 minutes
                if (done) mm.getModule("Exploration").disable();
            }
            case WAIT -> done = true; // already handled via timeout
        }

        if (done) {
            task.markComplete();
            if (client.player != null)
                client.player.sendSystemMessage(Component.literal("[MC BOT] ✓ Done: " + task.description));
            current = null;
        }
    }

    private void failCurrent(Minecraft client, String reason) {
        if (current != null) {
            current.markFailed(reason);
            if (client.player != null)
                client.player.sendSystemMessage(Component.literal(
                        "[MC BOT] ✗ Task failed (" + reason + "): " + current.description));
            current = null;
        }
    }

    private void applyMineTarget(AutoMineModule mine, String target) {
        switch (target.toLowerCase()) {
            case "iron"     -> mine.mineIron();
            case "gold"     -> mine.mineGold();
            case "diamond"  -> mine.mineDiamonds();
            case "emerald"  -> mine.mineEmeralds();
            case "ancient"  -> mine.mineAncient();
            case "coal"     -> mine.mineCoal();
            case "obsidian" -> mine.mineObsidian();
            default         -> mine.mineDiamonds();
        }
    }
}
